language: csharp
solution: CoCSharp.sln

mono:
    - latest

install:
    - nuget restore ./src/CoCSharp.sln
    - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory nunitrunner

script:
    - xbuild ./src/CoCSharp.sln
    - mono ./nunitrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./src/CoCSharp.Test/bin/Debug/CoCSharp.Test.dll
